sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - "8"
  - "10"
before_install:
  # Use newer yarn than that pre-installed in the Travis image.
  - curl -sSfL https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
    - yarn install
script:
    - yarn run lint
    - yarn test
after_success:
    - codecov
build: 
    - yarn run build